### PR TITLE
ICON RENDER FIX: UPDATED URL

### PR DESCRIPTION
**Pull request by bhargavshirin**
here also updated sorry haven't noticed before its fixed now

### CODE REVIEW

**Comment by bhargavshirin** [comment]
sir the icon is not loading so I added the new url for icon now its working

**Comment by bhargavshirin** [comment]
@philipkd @ucekmez @ceccode @JohnCHarrington

**Comment by bhargavshirin** [comment]
Screenshot 2024-10-02 at 9 25 20 PM

**Review by krish9797 — APPROVED** [review]

**Comment by bhargavshirin** [comment]
@philipkd @ucekmez @ceccode

**Comment by bhargavshirin** [comment]
@philipkd @ucekmez @ceccode please merge this

**Comment by doberst** [comment]
@bhargavshirin - thanks for fixing this!   👍

**Pull request merged**
