### PR TITLE
(typo):i've made some corrections to your documentation which clarify things

### PR DESCRIPTION
**Pull request by PrathameshSPawar**
I have made some corrections to your repository to help clarify certain aspects. These improvements aim to enhance the overall understanding and usability of the project. I hope they contribute positively to your work!

### CODE REVIEW

**Review by paulmcq — CHANGES_REQUESTED** [review]
line 730, `...from repo, We restrict...`: 'We' should not be capitalized.

**Comment by PrathameshSPawar** [comment]
i fixed this ok

**Review by paulmcq — APPROVED** [review]
Looks good

**Comment by doberst** [comment]
@PrathameshSPawar - thanks for your contribution!   👍

**Pull request merged**
