### PR TITLE
(typo):I've made some corrections to your documentation

### PR DESCRIPTION
**Pull request by PrathameshSPawar**
I have made some corrections to your repository to help clarify certain aspects. These improvements aim to enhance the overall understanding and usability of the project. I hope they contribute positively to your work!

### CODE REVIEW

**Review by paulmcq — CHANGES_REQUESTED** [review]
README.md line 839, add 'th' suffix to day: **No.**
Leave it as is. If this one is changed, then all dates must be changed to preserve consistent style.

**Review by paulmcq — CHANGES_REQUESTED** [review]
README.md line 734: These changes are not consistent with the rest of the document:
a) Capitalize 'Install'
b) Change '- e.g.' to '('
c) Add '.' after ')'
Consistent style aids reader comprehension.

**Comment by PrathameshSPawar** [comment]
Is this ok now?

**Comment by doberst** [comment]
@PrathameshSPawar - thanks for your updates and improvements!   👍

**Review by paulmcq — COMMENTED** [review]
Looks good to me. Thanks

**Pull request merged**
