### PR TITLE
Add chroma support

### PR DESCRIPTION
**Pull request by MacOS**
This pull request adds ```chroma``` support. And hence addresses issue #17 .

In particular, it

- updates LLMWareConfig
- updates EmbeddingHandler
- adds config class for ```chroma```
- adds an Embedding class for ```chroma```
- adds a unit test for ```chroma```
- adds example code.

### CODE REVIEW

**Comment by doberst** [comment]
@MacOS - awesome - excited to dig into this - we don't have an active Chroma environment set up - so please give a day or two so we can fully test the code - appreciate this contribution.   👍

**Comment by MacOS** [comment]
Happy to contribute! :grinning:

**Comment by doberst** [comment]
Nice job!    Well done.....

**Comment by doberst** [comment]
I made one tiny change - embeddings.py - line 2205 - the  searchiteration is thru results['ids'][0] (not results['ids']) - > this worked in my testing - but please take a second look and make sure that I didn't miss something subtle...

Also, will definitely add some comments on the 'persistent state' option just to make sure no one else is surprised.  Even though I read your comments, it took me a few iterations to figure out why the DB was not persisting anywhere.   😄

**Pull request merged**
